const { config } = require("dotenv");

config({
  path: `.env.development.local`,
});
const { PORT, MONGODB_URI, JWT_SECRET, JWT_ENDS_IN, ARCJET_ENV, ARCJET_KEY, EMAIL_ACCOUNT, EMAIL_PASSWORD, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET } = process.env;

module.exports = {
  PORT, MONGODB_URI, JWT_SECRET, JWT_ENDS_IN, ARCJET_ENV, ARCJET_KEY, EMAIL_ACCOUNT, EMAIL_PASSWORD, CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET
};
